// Generated by gencpp from file temoto/ChangeTf.msg
// DO NOT EDIT!


#ifndef TEMOTO_MESSAGE_CHANGETF_H
#define TEMOTO_MESSAGE_CHANGETF_H

#include <ros/service_traits.h>


#include <temoto/ChangeTfRequest.h>
#include <temoto/ChangeTfResponse.h>


namespace temoto
{

struct ChangeTf
{

typedef ChangeTfRequest Request;
typedef ChangeTfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeTf
} // namespace temoto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::temoto::ChangeTf > {
  static const char* value()
  {
    return "71007a2b9f41e14c743b5fced1fcc480";
  }

  static const char* value(const ::temoto::ChangeTf&) { return value(); }
};

template<>
struct DataType< ::temoto::ChangeTf > {
  static const char* value()
  {
    return "temoto/ChangeTf";
  }

  static const char* value(const ::temoto::ChangeTf&) { return value(); }
};


// service_traits::MD5Sum< ::temoto::ChangeTfRequest> should match 
// service_traits::MD5Sum< ::temoto::ChangeTf > 
template<>
struct MD5Sum< ::temoto::ChangeTfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::temoto::ChangeTf >::value();
  }
  static const char* value(const ::temoto::ChangeTfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::temoto::ChangeTfRequest> should match 
// service_traits::DataType< ::temoto::ChangeTf > 
template<>
struct DataType< ::temoto::ChangeTfRequest>
{
  static const char* value()
  {
    return DataType< ::temoto::ChangeTf >::value();
  }
  static const char* value(const ::temoto::ChangeTfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::temoto::ChangeTfResponse> should match 
// service_traits::MD5Sum< ::temoto::ChangeTf > 
template<>
struct MD5Sum< ::temoto::ChangeTfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::temoto::ChangeTf >::value();
  }
  static const char* value(const ::temoto::ChangeTfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::temoto::ChangeTfResponse> should match 
// service_traits::DataType< ::temoto::ChangeTf > 
template<>
struct DataType< ::temoto::ChangeTfResponse>
{
  static const char* value()
  {
    return DataType< ::temoto::ChangeTf >::value();
  }
  static const char* value(const ::temoto::ChangeTfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEMOTO_MESSAGE_CHANGETF_H
