// Generated by gencpp from file temoto/ChangeTfRequest.msg
// DO NOT EDIT!


#ifndef TEMOTO_MESSAGE_CHANGETFREQUEST_H
#define TEMOTO_MESSAGE_CHANGETFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace temoto
{
template <class ContainerAllocator>
struct ChangeTfRequest_
{
  typedef ChangeTfRequest_<ContainerAllocator> Type;

  ChangeTfRequest_()
    : first_person_perspective(false)
    , navigate(false)  {
    }
  ChangeTfRequest_(const ContainerAllocator& _alloc)
    : first_person_perspective(false)
    , navigate(false)  {
  (void)_alloc;
    }



   typedef uint8_t _first_person_perspective_type;
  _first_person_perspective_type first_person_perspective;

   typedef uint8_t _navigate_type;
  _navigate_type navigate;




  typedef boost::shared_ptr< ::temoto::ChangeTfRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::temoto::ChangeTfRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeTfRequest_

typedef ::temoto::ChangeTfRequest_<std::allocator<void> > ChangeTfRequest;

typedef boost::shared_ptr< ::temoto::ChangeTfRequest > ChangeTfRequestPtr;
typedef boost::shared_ptr< ::temoto::ChangeTfRequest const> ChangeTfRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::temoto::ChangeTfRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::temoto::ChangeTfRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace temoto

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'temoto': ['/home/conor/catkin_ws/src/temoto_intuitive_teleoperator/temoto/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::temoto::ChangeTfRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::temoto::ChangeTfRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temoto::ChangeTfRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temoto::ChangeTfRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temoto::ChangeTfRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temoto::ChangeTfRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::temoto::ChangeTfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71007a2b9f41e14c743b5fced1fcc480";
  }

  static const char* value(const ::temoto::ChangeTfRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71007a2b9f41e14cULL;
  static const uint64_t static_value2 = 0x743b5fced1fcc480ULL;
};

template<class ContainerAllocator>
struct DataType< ::temoto::ChangeTfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "temoto/ChangeTfRequest";
  }

  static const char* value(const ::temoto::ChangeTfRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::temoto::ChangeTfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool first_person_perspective\n\
bool navigate\n\
";
  }

  static const char* value(const ::temoto::ChangeTfRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::temoto::ChangeTfRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first_person_perspective);
      stream.next(m.navigate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeTfRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::temoto::ChangeTfRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::temoto::ChangeTfRequest_<ContainerAllocator>& v)
  {
    s << indent << "first_person_perspective: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.first_person_perspective);
    s << indent << "navigate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.navigate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEMOTO_MESSAGE_CHANGETFREQUEST_H
