// Generated by gencpp from file temoto/Command.msg
// DO NOT EDIT!


#ifndef TEMOTO_MESSAGE_COMMAND_H
#define TEMOTO_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace temoto
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : ns()
    , code(0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : ns(_alloc)
    , code(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ns_type;
  _ns_type ns;

   typedef uint8_t _code_type;
  _code_type code;


    enum { STOP = 0u };
     enum { PLAN = 1u };
     enum { EXECUTE = 2u };
     enum { GO = 3u };
     enum { ABORT = 255u };
 

  typedef boost::shared_ptr< ::temoto::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::temoto::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::temoto::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::temoto::Command > CommandPtr;
typedef boost::shared_ptr< ::temoto::Command const> CommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::temoto::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::temoto::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace temoto

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'temoto': ['/home/conor/catkin_ws/src/temoto_intuitive_teleoperator/temoto/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::temoto::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::temoto::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temoto::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temoto::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temoto::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temoto::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::temoto::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40f665deb8c3b4fb7be62824384735e4";
  }

  static const char* value(const ::temoto::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40f665deb8c3b4fbULL;
  static const uint64_t static_value2 = 0x7be62824384735e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::temoto::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "temoto/Command";
  }

  static const char* value(const ::temoto::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::temoto::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# List of predefined commands\n\
uint8 STOP=0\n\
uint8 PLAN=1\n\
uint8 EXECUTE=2\n\
uint8 GO=3\n\
\n\
uint8 ABORT=255\n\
\n\
# Namespace\n\
string ns\n\
\n\
# Command code\n\
uint8 code\n\
";
  }

  static const char* value(const ::temoto::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::temoto::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ns);
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::temoto::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::temoto::Command_<ContainerAllocator>& v)
  {
    s << indent << "ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ns);
    s << indent << "code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEMOTO_MESSAGE_COMMAND_H
