// Generated by gencpp from file leap_motion_controller/Finger.msg
// DO NOT EDIT!


#ifndef LEAP_MOTION_CONTROLLER_MESSAGE_FINGER_H
#define LEAP_MOTION_CONTROLLER_MESSAGE_FINGER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace leap_motion_controller
{
template <class ContainerAllocator>
struct Finger_
{
  typedef Finger_<ContainerAllocator> Type;

  Finger_()
    : type(0)
    , joint_position()  {
    }
  Finger_(const ContainerAllocator& _alloc)
    : type(0)
    , joint_position(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _joint_position_type;
  _joint_position_type joint_position;


    enum { TYPE_THUMB = 0u };
     enum { TYPE_INDEX = 1u };
     enum { TYPE_MIDDLE = 2u };
     enum { TYPE_RING = 3u };
     enum { TYPE_PINKY = 4u };
 

  typedef boost::shared_ptr< ::leap_motion_controller::Finger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leap_motion_controller::Finger_<ContainerAllocator> const> ConstPtr;

}; // struct Finger_

typedef ::leap_motion_controller::Finger_<std::allocator<void> > Finger;

typedef boost::shared_ptr< ::leap_motion_controller::Finger > FingerPtr;
typedef boost::shared_ptr< ::leap_motion_controller::Finger const> FingerConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leap_motion_controller::Finger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leap_motion_controller::Finger_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace leap_motion_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'leap_motion_controller': ['/home/conor/catkin_ws/src/temoto_intuitive_teleoperator/leap_motion_controller/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::leap_motion_controller::Finger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leap_motion_controller::Finger_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leap_motion_controller::Finger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leap_motion_controller::Finger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_motion_controller::Finger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_motion_controller::Finger_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leap_motion_controller::Finger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "395c50f3dc2ad1331c9fa184599413c8";
  }

  static const char* value(const ::leap_motion_controller::Finger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x395c50f3dc2ad133ULL;
  static const uint64_t static_value2 = 0x1c9fa184599413c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::leap_motion_controller::Finger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leap_motion_controller/Finger";
  }

  static const char* value(const ::leap_motion_controller::Finger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leap_motion_controller::Finger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 TYPE_THUMB = 0\n\
uint8 TYPE_INDEX = 1\n\
uint8 TYPE_MIDDLE = 2\n\
uint8 TYPE_RING = 3\n\
uint8 TYPE_PINKY = 4\n\
\n\
uint8 type\n\
geometry_msgs/Point[] joint_position\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::leap_motion_controller::Finger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leap_motion_controller::Finger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.joint_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Finger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leap_motion_controller::Finger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leap_motion_controller::Finger_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "joint_position[]" << std::endl;
    for (size_t i = 0; i < v.joint_position.size(); ++i)
    {
      s << indent << "  joint_position[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.joint_position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEAP_MOTION_CONTROLLER_MESSAGE_FINGER_H
